// für DEV

// Lösche alle User
###
DELETE  https://localhost/Users/
Authorization: {{adminToken}}



// Re-test Meilenstein 1, es sollte der Standard-Admin in der Datenbank sein
###
GET https://localhost/publicUsers


// Login mit Basic Authentication mit korrekten Credentials admin:123
###
# @name loginAdminCorrect
GET https://localhost/authenticate
Authorization: Basic YWRtaW46MTIz

// Login mit Basic Authentication mit falschen Credentials
###
GET https://localhost/authenticate
Authorization: Basic admin:1234

@adminToken = {{loginAdminCorrect.response.headers.Authorization}}



### Auflisten aller Nutzer ohne Token
GET https://localhost/users



### Auflisten aller Nutzer mit Token(Admin)
GET https://localhost/users
Authorization: {{adminToken}}



### Abrufen eines konkreten Users per User-ID
GET https://localhost/users/manfred
Authorization: {{adminToken}}


// Lösche alle User
###
DELETE  https://localhost/Users/
Authorization: {{adminToken}}



// Lege zweiten User an
###
POST https://localhost/users
Authorization: {{adminToken}}
Content-Type: application/json

{
    "userID": "manfred",
    "userName": "Manfred Mustermann",
    "password": "asdf",
    "email": "asbc@de.com"
}

###
PUT https://localhost/users/manfred
Authorization: {{adminToken}}
Content-Type: application/json

{
    "email": "Manfred Maier"
}

### Auflisten aller Nutzer mit Token(Admin)
https://localhost/users
Authorization: {{adminToken}}







//
// Forum Tests
//
### Auflisten aller Foren ohne Token


// Lösche alle Threads FÜR DEV
###
DELETE  https://localhost/forumThreads/
Authorization: {{adminToken}}


### Auflisten der Foren des aktuellen users
GET https://localhost/forumThreads/myForumThreads
Authorization: {{adminToken}}


### Auflisten aller Foren ohne Token
GET https://localhost/forumThreads

// Lege ein ersten Forum an, der Administrator ist owner
###
# @name createForumRequest
POST https://localhost/forumThreads
Authorization: {{adminToken}}
Content-Type: application/json

{
    "name": "Mein erstes Forum",
    "description": "Das ist ein erstes Forum, das ich im Rahmen der Tests angelegt habe"
}

###
@forumThreadID = {{createForumRequest.response.body._id}}

### Auflisten aller Foren ohne Token
GET https://localhost/forumThreads

### Auflisten der Foren des aktuellen users
GET https://localhost/forumThreads/myForumThreads
Authorization: {{adminToken}}

// Login mit Basic Authentication als manfred mit korrekten Credentials admin:123
###
# @name loginManfredCorrect
GET https://localhost/authenticate
Authorization: Basic manfred:asdf
###
@manfredToken = {{loginManfredCorrect.response.headers.Authorization}}

### Auflisten aller ForumThreads von eingelogtem User manfred
GET https://localhost/forumThreads/myForumThreads
Authorization: {{manfredToken}}

### Forum mit einer bestimmten ID abrufen
GET https://localhost/forumThreads/{{forumThreadID}}

### Forum mit WebMessageBodyStyle Wrapped, nicht relevant für Abgabe
GET https://localhost/forumThreads/{{forumThreadID}}
WebMessageBodyStyle: Wrapped

### Ändere die forumDescription in dem existierenden Forum
PUT https://localhost/forumThreads/{{forumThreadID}}
Authorization: {{adminToken}}
Content-Type: application/json

{
    "description": "Das ist der neue Text"
}

### Auflisten der Foren des Administrators
GET https://localhost/forumThreads?ownerID=admin

### Foren für admin auflisten (es sollte 1 sein)
GET https://localhost/forumThreads?ownerID=admin


###
# @name createForumRequest
POST https://localhost/forumThreads
Authorization: {{manfredToken}}
Content-Type: application/json

{
    "name": "Manfreds erstes Forum",
    "description": "Das ist der Text von Manfred"
}

### Auflisten der Foren für den User manfred
GET https://localhost/forumThreads?ownerID=manfred








### Forumnachrichten für einen bestimmten Forum-Thread abrufen
GET https://localhost/forumThreads/{{forumThreadID}}/forumMessages

### Auflisten aller Forumnachrichten ohne Token
https://localhost/forumMessages

###
# @name createForumMessageRequest
POST https://localhost/forumMessages
Authorization: {{adminToken}}
Content-Type: application/json

{
    "forumThreadID": "{{forumThreadID}}",
    "title": "Meine erste Forumnachricht",
    "text": "Das wollte ich nur kurz in das Forum schreiben."
}
###
@forumMessageID = {{createForumMessageRequest.response.body._id}}

###
// Anlegen mit falscher Forum ID
POST https://localhost/forumMessages
Authorization: {{adminToken}}
Content-Type: application/json

{
    "forumThreadID": "Gibt es nicht",
    "title": "Meine erste Forumnachricht",
    "text": "Das wollte ich nur kurz in das Forum schreiben."
}

### Auflisten aller Forumnachrichten für Forum über Suchparameter
GET https://localhost/forumMessages?forumThreadID={{forumThreadID}}

### Auflisten aller Forumnachrichten für Forum über nachgelagerte Suche
GET https://localhost/forumThreads/{{forumThreadID}}/forumMessages

### Löschen einer Forumnachrichten
DELETE  https://localhost/forumMessages/{{forumMessageID}}
Authorization: {{adminToken}}

### Lösche Forum-Thread
DELETE  https://localhost/forumThreads/{{forumThreadID}}
Authorization: {{adminToken}}
