### authentication über den body
POST http://localhost:8080/authenticate/login
Content-Type: application/json

{
    "userID": "peter",
    "password": "1253"
}


### basic authentication
POST http://localhost:8080/authenticate/loginBasic
Authorization: Basic dGF0aToxMjM=

