### authentication über den body
POST http://localhost:8080/authenticate/
Content-Type: application/json

{
    "userID": "admin",
    "password": "123"
}


### basic authentication
GET http://localhost:8080/authenticate/
Authorization: Basic dGF0aToxMjM=

